name: viajabara
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  book_my_seat: ^1.0.1
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.0.2
  font_awesome_flutter: ^10.6.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  lottie: ^2.7.0
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600
