FROM node:21.2.0-bullseye as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN export NODE_OPTIONS=--openssl-legacy-provider ; npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf